export const productList = [
    {
      id: 0,
      name: "iphone",
      title: "Apple iphone 15 Pro Max",
      imgSrc: 'https://innergo.store/pol_pl_iPhone-15-Pro-Max-512GB-White-Titanium-35536_1.webp',
      screen: "screen 6.1",
      processor: "Apple A16 Bionic",
      memory: "256gb",
      system: "ios 15",
      price: 1599,
      free: "free Shipment",
    },
  
    {
      id: 1,
      name: "iphone",
      title: "Apple iphone 13 Pro Max",
      imgSrc: "https://acom.pl/media/webp_image/catalog/product/cache/0f7431f5367b37c067ffd8dcd36cc722/a/p/apple-iphone-13-pro-max-128gb-alpejska-zielen-alpine-green_1.webp",
      screen: "screen 6.1",
      rocessor: "Apple A16 Bionic",
      memory: "256gb",
      system: "ios 15",
      price: 1299,
      free: "free Shipment",
    },
    {
      id: 2,
      name: "iphone",
      title: "Apple iphone 12",
      imgSrc: "https://innergo.store/pol_pl_iPhone-12-Purple-64GB-28657_1.webp",
      rocessor: "Apple A16 Bionic",
      screen: "screen 6.1",
      memory: "256gb",
      system: "ios 15",
      price: 1199,
      free: "free Shipment",
    },
    {
      id: 3,
      name: "iphone",
      title: "Apple iphone 15 Pro Max",
      imgSrc: "https://innergo.store/pol_pl_iPhone-15-Pro-Max-256GB-Natural-Titanium-35533_5.webp",
      screen: "screen 6.1",
      processor: "Apple A16 Bionic",
      memory: "256gb",
      system: "ios 15",
      price: 1599,
      free: "free Shipment",
    },
  
    {
      id: 4,
      name: "iphone",
      title: "Apple iphone 13 Pro Max",
      imgSrc: "https://acom.pl/media/webp_image/catalog/product/cache/0f7431f5367b37c067ffd8dcd36cc722/a/p/apple-iphone-13-pro-max-256gb-srebrny-silver_1.webp",
      screen: "screen 6.1",
      rocessor: "Apple A16 Bionic",
      memory: "256gb",
      system: "ios 15",
      price: 1299,
      free: "free Shipment",
    },
    {
      id: 5,
      name: "iphone",
      title: "Apple iphone 12",
      imgSrc: "https://acom.pl/media/webp_image/catalog/product/cache/0f7431f5367b37c067ffd8dcd36cc722/a/p/apple-iphone-12-64gb-fioletowy-purple_1.webp",
      rocessor: "Apple A16 Bionic",
      screen: "screen 6.1",
      memory: "256gb",
      system: "ios 15",
      price: 1199,
      free: "free Shipment",
    },
  ];